### ISSUE TITLE
Get geographic data for Venezuela's parishes

### ISSUE THREAD

**Issue by luiscape** [HackForVenezuela/data-collection-miconvive#5]
This project deals with the mapping of crimes to a number of Parishes. We need the geographic data for those parishes. That data most likely need to have the following properties:

* polygons
* name
* id

The latter `id` property may be inherent to this dataset -- and, hence, needs to be used elsewhere as a derivate of this dataset.

cc **Maria**

**Comment by luiscape** [comment]
The following datasets (provided by a GIS professional from Venezuela) seem to provide the required information for mapping purposes. 

https://tapiquen-sig.jimdo.com/descargas-gratuitas/venezuela/capas-base/

I'll check that the data can be mapped to the data from the spreadsheet before closing this issue.

**Comment by luiscape** [comment]
A bit more info:

* the data has a timestamp for 2015 -- that seems that it was updated last
* I have downloaded the dataset `Parroquias de Caracas` which provides a dataset with more detail than the other `Parroquias de Caracas`, but with the same units. Using this dataset instead of the other may provide a better user experience. Here's a visual difference:
![](https://image.jimcdn.com/app/cms/image/transf/dimension=514x10000:format=png/path/s0001777a9ca986dd/image/if07d583d63f43278/version/1424971524/image.png)
![](https://image.jimcdn.com/app/cms/image/transf/dimension=514x10000:format=png/path/s0001777a9ca986dd/image/i9eed7c31dd187415/version/1462285652/image.png)
* While the `Parroquias de Caracas` is mode detailed, it is also a much larger database (18mb). That file size will make it very difficult to load on the browser -- more so on a slow connection.

**Comment by luiscape** [comment]
I'm closing this now. I've added the database of locations to the repository in the `visualization` branch.

**Comment by williamFalcon** [comment]
@luiscape 👍

**Comment by mariaignaciac** [comment]
These are the parish coordinates that Niko from Caracas Mi Convive just sent me. [Coordenadas Parroquias CCS.xlsx](https://github.com/HackForVenezuela/data-collection-miconvive/files/1485939/Coordenadas.Parroquias.CCS.xlsx)
